language: node_js
node_js:
  - '12'
cache:
  yarn: true
deploy:
  provider: npm
  email: axyzxp@gmail.com
  api_key:
    secure: pEZCiJZXf08JDwC51BYQ1UF326J6IwBmOXQg8HJUQBST7FGnU1a+U5AnfISzgXNibuthxbfcqYg6qdLZxTXXBJWgdeW9cSlzFgSLALegJNLnjfTWQnDjvC3opSx0lAra62sT4nF1kep9ofxdisB1X0D2pN8G0oytv53PExvDh/5OUca7L9Re+3GMPuKdCn3InbF8eYyWsZZ3/VDQlrnoBeNU/Kjq5PA/P77VVkZOHGUvRRDShFuVTAcI72oxuSEG5F6u6e8AfeXBwUSZOYLv2xQyPetrLb/MskwKTMlAlH3/pql0pGKVbM5mXWc4jQZ2FeMbxtk8HioFcgNSkzktCyRtTpyDfxqhjqQWnjdCgkzJTC2V5JTZwLiS8OF+yzQcJ/B209oTsPpyD4/tSnP1empH+q4bclEsvoXKuQ2VfLcDs60N5kEMB8rZlc4Tgs8X3ETV+tGlU+fqWxVWp/KDaX1rAnJzDi69dM5sDcsb/syinOH7GTSTG+Z0SdyNL6fEFzPhutiQsxKJQOnlF4+vxwCf2Hv/t8MOxQiOVZL4hf+y7XpqJnxSJb5mAFV7H/UWqng52wVF3VH3VcnlbiknIIU0LEueN8PLxfxNd4RoMIhbPMquNp/HYyTpZUIu0TOMa34oSbufOp2vmbQ9ErfKVdXElb+38w4FQTJ/p4ns54w=
  skip_cleanup: true
  on:
    tags: true
    repo: utilitycss/atomic
